[build]
target = "riscv64gc-unknown-linux-musl"


[profile.release]
lto = true
strip = true
opt-level = 3  # Optimize for size.
panic = "abort"


[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-linux-musl-cc"